on:
  push:
    branches:
    - main
jobs:
  install_jdk:
    name: deploy to staging
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 11
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '11'
          distribution: 'temurin'  # Correct distribution for AdoptOpenJDK (now Adoptium)
          
      - name: Verify Java installation
        run: java -version
